In [13]:
import numpy as np
from IPython.display import Image, display

In [ ]:
display(Image(filename='./Assets/eigen_pair.png'))

In [2]:
A = np.array([[2, -2, 3], [1, 1, 1], [1, 3, -1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [3]:
# calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

In [5]:
print(eigenvalues)

[ 3.  1. -2.]


In [6]:
print(eigenvectors)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [7]:
A = np.array([[2, 0, 0], [0, 1, 0], [0, 0, -1]])

In [8]:
A

array([[ 2,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [9]:
values, vectors = np.linalg.eig(A)

In [10]:
print(values)

[ 2.  1. -1.]


In [12]:
print(vectors)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
